"""add_last_editor_id_to_documents

Revision ID: 99e612fdedfc
Revises: b65f35be67b7
Create Date: 2025-07-22 13:02:46.571955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e612fdedfc'
down_revision: Union[str, None] = 'b65f35be67b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_versions', 'change_description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # 手动添加 last_editor_id 字段
    op.add_column('documents', sa.Column('last_editor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documents', 'users', ['last_editor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'version',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_versions', 'change_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    
    # 手动删除 last_editor_id 字段
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'last_editor_id')
    # ### end Alembic commands ###
