"""fix_foreign_key_relationships

Revision ID: e34856f0083d
Revises: 
Create Date: 2025-07-18 19:52:40.133400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e34856f0083d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_versions_id', table_name='document_versions')
    op.drop_table('document_versions')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('cas_user_id', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('cas_attributes', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_users_cas_user_id'), 'users', ['cas_user_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_cas_user_id'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'cas_attributes')
    op.drop_column('users', 'cas_user_id')
    op.drop_column('users', 'password_hash')
    op.create_table('document_versions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('change_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('changes_diff', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='document_versions_changed_by_fkey'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='document_versions_document_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='document_versions_pkey')
    )
    op.create_index('ix_document_versions_id', 'document_versions', ['id'], unique=False)
    # ### end Alembic commands ###
