"""fix_relationships_and_create_all_tables

Revision ID: f708bbd7335b
Revises: 
Create Date: 2025-07-18 19:32:02.006731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f708bbd7335b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_users_cas_user_id', table_name='users')
    op.drop_column('users', 'cas_user_id')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'cas_attributes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cas_attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('cas_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_index('ix_users_cas_user_id', 'users', ['cas_user_id'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
